-- init_db.sql
-- Creates DBASSIGNMENT and tables USER and STUDENT (exact schema as required)

CREATE DATABASE IF NOT EXISTS `DBASSIGNMENT`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE `DBASSIGNMENT`;

-- USER table
CREATE TABLE IF NOT EXISTS `USER` (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  role ENUM('admin', 'student') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- STUDENT table
CREATE TABLE IF NOT EXISTS `STUDENT` (
  student_id INT AUTO_INCREMENT PRIMARY KEY,
  matric_no VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  ic_no VARCHAR(20) NOT NULL UNIQUE,
  gender VARCHAR(10) NOT NULL,
  programme VARCHAR(100) NOT NULL,
  faculty VARCHAR(100) NOT NULL,
  semester INT NOT NULL,
  email VARCHAR(100),
  phone_no VARCHAR(20),
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;